# Generated by Django 5.0.8 on 2024-10-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reparacion', models.CharField(max_length=15)),
                ('reparacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reparacion', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='reportemecanico',
            name='tiempo_acumulado',
            field=models.IntegerField(default=None),
        ),
    ]
