# Generated by Django 5.0.8 on 2024-10-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportereparacion',
            old_name='id_ingreso',
            new_name='id_entrada',
        ),
        migrations.RenameField(
            model_name='reportereparacion',
            old_name='tipo_ingreso',
            new_name='tipo_entrada',
        ),
    ]
