# Generated by Django 5.0.8 on 2024-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0002_rename_id_ingreso_reportereparacion_id_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportereparacion',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado')], default='Pendiente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportereparacion',
            name='tipo_entrada',
            field=models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('RESCATE', 'Rescate'), ('PREVENTIVO', 'Preventivo'), ('ACCIDENTE', 'Accidente')], max_length=20, null=True),
        ),
    ]
