# Generated by Django 5.0.8 on 2024-10-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0002_fallo_tiporeparacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fallo',
            new_name='Reparacion',
        ),
    ]
