# Generated by Django 5.0.8 on 2024-10-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0003_alter_reportereparacion_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportereparacion',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportereparacion',
            name='id_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_operaciones.reporteentrada'),
        ),
        migrations.AlterField(
            model_name='reportereparacion',
            name='tipo_entrada',
            field=models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('RESCATE', 'Rescate'), ('PREVENTIVO', 'Preventivo'), ('ACCIDENTE', 'Accidente')], default='Sin Asignar', max_length=20),
        ),
    ]
