# Generated by Django 5.0.8 on 2024-10-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0004_alter_reparacion_tipo_reparacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportemecanico',
            name='diagnosito_mecanico',
        ),
        migrations.RemoveField(
            model_name='reportemecanico',
            name='subreparacion',
        ),
        migrations.RemoveField(
            model_name='reportemecanico',
            name='tipo_reparacion',
        ),
        migrations.AddField(
            model_name='reportemecanico',
            name='reparacion',
            field=models.ManyToManyField(blank=True, related_name='reparaciones', to='reporte_operaciones.reparacion'),
        ),
        migrations.AlterField(
            model_name='reportemecanico',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reportemecanico',
            name='hora_inicio',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reportemecanico',
            name='tiempo_acumulado',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
