# Generated by Django 5.0.8 on 2024-10-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0005_remove_reportemecanico_diagnosito_mecanico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportemecanico',
            old_name='reparacion',
            new_name='reparacion_selecionadas',
        ),
    ]
