# Generated by Django 5.0.8 on 2024-10-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0007_rename_reparacion_selecionadas_reportemecanico_reparacion_selecionada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='reparacion',
            new_name='nombre',
        ),
    ]
