# Generated by Django 5.0.8 on 2024-10-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0008_rename_reparacion_reparacion_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='nombre',
            new_name='reparacion',
        ),
    ]
