# Generated by Django 5.0.8 on 2024-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0012_remove_reportereparacion_id_reporte_mecanico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioautocar',
            name='departamento',
            field=models.CharField(choices=[('OPERACIONES', 'Operaciones'), ('TALLER', 'Taller'), ('ALMACEN', 'Almacen'), ('MECANICO', 'Mecanico'), ('SUPERVISOR', 'Supervisor'), ('JEFE_DEPARTAMENTO', 'Jefe Departamento')], max_length=20),
        ),
    ]
