# Generated by Django 5.0.8 on 2024-10-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0013_alter_usuarioautocar_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportemecanico',
            name='hora_suspendido',
        ),
        migrations.AlterField(
            model_name='reportemecanico',
            name='tiempo_acumulado',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reportereparacion',
            name='id_reporte_mecanico',
            field=models.ManyToManyField(blank=True, to='reporte_operaciones.reportemecanico'),
        ),
    ]
