# Generated by Django 5.0.8 on 2024-11-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0016_rename_reporte_reparacion_reportemecanico_reportereparacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportemecanico',
            old_name='reporteReparacion',
            new_name='reporte_reparacion',
        ),
    ]
