# Generated by Django 5.0.8 on 2024-11-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0017_rename_reportereparacion_reportemecanico_reporte_reparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_estacion', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
