# Generated by Django 5.0.8 on 2024-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0018_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='estado',
            field=models.CharField(choices=[('SI', 'Disponible'), ('NO', 'No Disponible')], default='SI', max_length=15),
        ),
    ]
