# Generated by Django 5.0.8 on 2024-11-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0019_estacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadBuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_unidad', models.CharField(choices=[('NORTE', 'Norte'), ('SUR', 'Sur'), ('HOTELES', 'Hoteles')], max_length=20)),
                ('cantidad', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='reportereparacion',
            name='estacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='reporte_operaciones.estacion'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado',
            field=models.CharField(choices=[('SI', 'Disponible'), ('NO', 'Ocupado')], default='SI', max_length=15),
        ),
    ]
