# Generated by Django 5.0.8 on 2024-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0020_cantidadbuses_reportereparacion_estacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemecanico',
            name='estatus',
            field=models.CharField(blank=True, default='Inactivo', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportereparacion',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Terminado', 'Terminado')], default='Pendiente', max_length=20),
        ),
    ]
