# Generated by Django 5.0.8 on 2024-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0021_reportemecanico_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportereparacion',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Sin Asignar', 'Sin Asignar'), ('Terminado', 'Terminado'), ('Suspendido', 'Suspendido')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioautocar',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('MOTOR', 'Motor'), ('FRENOS', 'Frenos'), ('SUSPENSION', 'Suspensión'), ('ELECTRICO', 'Eléctrico'), ('RESCATISTA', 'Rescatista'), ('MUELLERO', 'Muellero'), ('TEC_PINTOR', 'Técnico Pintor'), ('PINTOR', 'Pintor'), ('AYU_ELECTRICO', 'Ayudante Eléctrico'), ('CARROCERO', 'Carrocero'), ('AYU_CARROCERO', 'Ayudante Carrocero'), ('SOLDADOR', 'Soldador'), ('LAVADO_MOTOR', 'Lavadores de Motores'), ('TEC_MEC_AUTOMOTRIZ', 'Técnico Mecánico Automotriz'), ('TEC_ELEC_AUTOMOTRIZ', 'Técnico Electrico Automotriz')], max_length=20, null=True),
        ),
    ]
