# Generated by Django 5.0.8 on 2024-11-17 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_operaciones', '0022_alter_reportereparacion_estatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporteentrada',
            old_name='descripcion_incidente',
            new_name='descripción_incidente',
        ),
    ]
