# Generated by Django 5.0.8 on 2024-09-23 01:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import reporte_operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_conductor', models.CharField(max_length=20)),
                ('apellido_conductor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id_mecanico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mecanico', models.CharField(max_length=30)),
                ('apellido_mecanico', models.CharField(max_length=30)),
                ('especialidad_mecanico', models.CharField(choices=[(reporte_operaciones.models.EspecialidadMecanico['CARROCERIA'], 'Carroceria'), (reporte_operaciones.models.EspecialidadMecanico['ELECTRICO'], 'Electrico'), (reporte_operaciones.models.EspecialidadMecanico['PINTURA'], 'Pintura')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PiezasRepuesto',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pieza', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.CharField(max_length=30)),
                ('modelo_unidad', models.CharField(max_length=30)),
                ('ano_unidad', models.CharField(max_length=30)),
                ('zona_unidad', models.CharField(choices=[(reporte_operaciones.models.ZonaVehiculos['NORTE'], 'Norte'), (reporte_operaciones.models.ZonaVehiculos['SUR'], 'Sur'), (reporte_operaciones.models.ZonaVehiculos['CENTRO'], 'Centro')], max_length=20)),
                ('kilometraje', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteEntrada',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('fecha_terminado', models.DateField(default=None)),
                ('descripcion_incidente', models.CharField(max_length=255)),
                ('kilometraje_nuevo', models.CharField(max_length=10)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporte_operaciones.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.DateField(default=None)),
                ('fecha_terminado', models.DateTimeField(default=None)),
                ('hora_termiando', models.DateTimeField(default=None)),
                ('diagnosito_mecanico', models.CharField(max_length=255)),
                ('tiempo_acumulado', models.CharField(max_length=100)),
                ('id_mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_operaciones.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteReparacion',
            fields=[
                ('id_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ingreso', models.CharField(choices=[(reporte_operaciones.models.TipoIngreso['CORRECTIVO'], 'Correctivo'), (reporte_operaciones.models.TipoIngreso['RESCATE'], 'Rescate'), (reporte_operaciones.models.TipoIngreso['PREVENTIVO'], 'Preventivo'), (reporte_operaciones.models.TipoIngreso['ACCIDENTE'], 'Accidente')], max_length=20)),
                ('id_reporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporte_operaciones.reporteentrada')),
            ],
        ),
        migrations.CreateModel(
            name='PiezasReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_operaciones.piezasrepuesto')),
                ('reporte_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_operaciones.reportereparacion')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAutocar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('departamento', models.CharField(choices=[(reporte_operaciones.models.Departamento['OPERACIONES'], 'Operaciones'), (reporte_operaciones.models.Departamento['TALLER'], 'Taller'), (reporte_operaciones.models.Departamento['ALMACEN'], 'Almacen'), (reporte_operaciones.models.Departamento['REPARACION'], 'Mecanico')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarioautocar_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarioautocar_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reporteentrada',
            name='reporte_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporte_operaciones.usuarioautocar'),
        ),
        migrations.AddField(
            model_name='reporteentrada',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporte_operaciones.vehiculos'),
        ),
        migrations.CreateModel(
            name='MecanicosAsignados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_operaciones.mecanico')),
                ('reporte_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_operaciones.reportereparacion')),
            ],
            options={
                'unique_together': {('reporte_reparacion', 'mecanico')},
            },
        ),
    ]
